apps/configuraciones/urls.py
from django.urls import path

from . import views

app_name = 'configuraciones'

urlpatterns = [
    path('casillas/', views.ListarCasillas.as_view(), name='casillas'),
    path('casillas/crear/', views.CrearCasilla.as_view(), name='crear_casilla'),
    path('casillas/editar/<int:pk>/', views.EditarCasilla.as_view(), name='editar_casilla'),
    path('casillas/predestroy/<int:pk>/', views.predestroy_casilla, name='predestroy_casilla'),
    path('casillas/destroy/<int:pk>/', views.destroy_casilla, name='destroy_casilla'),
    path('configuracion/crear/', views.CrearConfiguracion.as_view(), name='crear_configuracion'),
    path('configuracion/editar/<int:pk>/', views.EditarConfiguracion.as_view(), name='editar_configuracion'),
]

apps/master/urls.py
from django.urls import path
from . import views

app_name = 'master'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.menu, name='menu'),
]

apps/usuarios/urls.py
from django.urls import path
from .formularios import UserLoginForm
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.ListarUsuarios.as_view(), name="index"),
    path('registrar', views.Registrar.as_view(), name="registrar"),
    path('login',views.Login.as_view(authentication_form=UserLoginForm),name='login'),
    path('perfil/<int:pk>',views.Profile.as_view(),name='perfil'),
    path('crear',views.CrearUsuario.as_view(),name='crear'),
    path('editar/<int:pk>',views.EditarUsuario.as_view(),name='editar'),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
]

despachador_correos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500

handler400 = 'despachador_correos.views.bad_request'
handler403 = 'despachador_correos.views.permission_denied'
handler404 = 'despachador_correos.views.page_not_found'
handler500 = 'despachador_correos.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.master.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('configuraciones/', include('apps.configuraciones.urls')),
    path('correos/', include('apps.correos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/configuraciones/models.py
from django.db import models

# Create your models here.
class Casilla(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email
    
class TipoServicio(models.Model):
    nombre = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class Configuracion(models.Model):
    protocolo = models.CharField(max_length=10,blank=True,null=True)
    id_usuario = models.CharField(max_length=255,blank=True,null=True)
    id_tenant = models.CharField(max_length=255,blank=True,null=True)
    id_app = models.CharField(max_length=255,blank=True,null=True)
    id_key = models.CharField(max_length=255,blank=True,null=True)
    api_key = models.CharField(max_length=255,blank=True,null=True)
    casilla = models.ForeignKey(Casilla, on_delete=models.PROTECT)
    tipo_servicio = models.ForeignKey(TipoServicio, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/configuraciones/views.py
from django.shortcuts import redirect
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .models import Configuracion, Casilla
from .formularios import FormularioCasilla, FormularioConfiguracion


# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListarCasillas(ListView):
    template_name = "configuraciones/casillas_list.html"
    model = Casilla

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['appname'] = "casillas"
        return context
    
    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        else:
            return redirect(reverse_lazy('master:menu'))
        
@method_decorator(login_required, name='dispatch')
class CrearCasilla(CreateView):
    template_name = "configuraciones/configuraciones.html"
    model = Casilla
    form_class = FormularioCasilla
    success_url = reverse_lazy("configuraciones:casillas")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['legend'] = "Crear Casilla"
        context['appname'] = "casillas"
        return context

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        else:
            return redirect(reverse_lazy('master:menu'))
        
@method_decorator(login_required, name='dispatch')
class EditarCasilla(UpdateView):
    template_name = "configuraciones/configuraciones.html"
    model = Casilla
    form_class = FormularioCasilla
    success_url = reverse_lazy("configuraciones:casillas")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['legend'] = "Editar Casilla"
        context['appname'] = "casillas"
        return context

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        else:
            return redirect(reverse_lazy('master:menu'))
        
@login_required(login_url="/")
def predestroy_casilla(request, pk):
    if request.method == "GET":
        try:
            casilla = Casilla.objects.get(id=pk)
        except:
            return redirect("usuarios:index")
        context={
            'id' : casilla.id,
            'email' : casilla.email,
        }
        return JsonResponse(context)
    return redirect("usuarios:index")

@login_required(login_url="/")
def destroy_casilla(request, pk):
    if request.method == "GET":
        try:
            casilla = Casilla.objects.get(id=pk)
            casilla.delete()
            messages.success(request, "Casilla eliminada correctamente",extra_tags='success')
        except:
            messages.success(request, "Error al eliminar la casilla",extra_tags='danger')
    return redirect("configuraciones:casillas")

# Crear configuracion.
@method_decorator(login_required, name='dispatch')
class CrearConfiguracion(CreateView):
    template_name = "configuraciones/configuraciones.html"
    model = Configuracion
    form_class = FormularioConfiguracion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['legend'] = "Crear Configuración"
        context['appname'] = "Nueva Configuración"
        return context

    def get(self, *args, **kwargs):
        if Configuracion.objects.count() != 0:
            ultimo_id = Configuracion.objects.last().id 
            return redirect("configuraciones:editar_configuracion",pk = ultimo_id)
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        else:
            return redirect("marter:menu")
        
    def get_success_url(self):
        return reverse_lazy('configuraciones:editar_configuracion', kwargs={'pk': self.object.id})
    
# Modificar configuracion.
@method_decorator(login_required, name='dispatch')
class EditarConfiguracion(UpdateView):
    template_name = "configuraciones/configuraciones.html"
    model = Configuracion
    form_class = FormularioConfiguracion

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['legend'] = "Editar Configuración"
        context['appname'] = "configuraciones"
        return context

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return super().get(*args, **kwargs)
        else:
            return redirect(reverse_lazy('master:menu'))
   
    def get_object(self):
        return Configuracion.objects.last()
    
    def get_success_url(self):
        return reverse_lazy('configuraciones:editar_configuracion', kwargs={'pk': self.object.id})

templates/configuraciones/casillas_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    <a href="{% url 'configuraciones:crear_casilla' %}"
        class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i class="fas fa-plus-circle"></i> Agregar
        Casilla</a>
</div>

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

<div class=" mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Email</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for casilla in object_list %}
            <tr>
                <td>{{casilla.id}}</td>
                <td>{{casilla.email}}</td>
                <td>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'configuraciones:editar_casilla' pk=casilla.id %}" id="edit"><i
                            class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'configuraciones:predestroy_casilla' pk=casilla.id %}" href="">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar la siguiente
                    Casilla?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>

            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

{% block javascript %}
<script>
    $(".dataTable").on('click', '.open-modal', function () {
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                Datos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Email: " + data['email'] + "</p>";
                $(".modal-body").append(Datos);
                $("#delete").click(function () {
                    window.location.href = "/configuraciones/casillas/destroy/" + data[
                        "id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}

templates/configuraciones/configuraciones.html
{% extends user.is_authenticated|yesno:"base.html,registration/base_login.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

{% if user.is_authenticated %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
            <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
                class="far fa-arrow-alt-circle-left"></i> Volver al
            menú</a>
</div>
<div class="col-8 p-3 mx-auto border border-primary">
    <form enctype="multipart/form-data" class="text-dark" method="POST" class="rounded-3 text-white">
        {% else %}
        <form enctype="multipart/form-data" method="POST" class="rounded-3 text-white">
            {% endif %}
            <h2 class="text-center">{{legend}}</h2>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {% crispy form %}
        </form>
</div>

{% endblock contenido %}

templates/configuraciones/configuraciones_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    <a href="{% url 'usuarios:crear' %}" class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i
            class="fas fa-plus-circle"></i> Agregar Usuario</a>
</div>
<div class=" mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in object_list %}
            <tr>
                <td>{{usuario.id}}</td>
                <td>{{usuario.first_name}}</td>
                <td>{{usuario.last_name}}</td>
                <td>{{usuario.email}}</td>
                <td>
                    {% if not usuario.is_superuser %}
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'usuarios:editar' pk=usuario.id %}" usuario="{{usuario.id}}" id="edit"><i
                            class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'usuarios:predestroy' pk=usuario.id %}" href="">
                        <i class="fas fa-trash"></i> </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar al siguiente
                    Usuario?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>

            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

{% block javascript %}
<script>
    $(".dataTable").on('click', '.open-modal', function () {
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                Datos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'] + " " + data['apellido'] +
                    "</p> <p notempty='not'> Email: " +
                    data['email'] +
                    "</p>";
                $(".modal-body").append(Datos);
                $("#delete").click(function () {
                    window.location.href = "/usuarios/destroy/" + data["id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}