apps/configuraciones/urls.py
from django.urls import path

from . import views

app_name = 'configuraciones'

urlpatterns = [
    path('casillas/', views.ListarCasillas.as_view(), name='casillas'),
    path('casillas/crear/', views.CrearCasilla.as_view(), name='crear_casilla'),
    path('casillas/editar/<int:pk>/', views.EditarCasilla.as_view(), name='editar_casilla'),
    path('casillas/predestroy/<int:pk>/', views.predestroy_casilla, name='predestroy_casilla'),
    path('casillas/destroy/<int:pk>/', views.destroy_casilla, name='destroy_casilla'),
    path('configuracion/crear/', views.CrearConfiguracion.as_view(), name='crear_configuracion'),
    path('configuracion/editar/<int:pk>/', views.EditarConfiguracion.as_view(), name='editar_configuracion'),
]

apps/correos/urls.py
from django.urls import path

from . import views

app_name = 'correos'

urlpatterns = [
    path('', views.ListarCorreos.as_view(), name="correos"),
    path('ejecutivos', views.ListarEjecutivos.as_view(), name="ejecutivos"),
    path('crear_ejecutivo',views.CrearEjecutivo.as_view(),name='crear_ejecutivo'),
    path('editar_ejecutivo/<int:pk>',views.EditarEjecutivo.as_view(),name='editar_ejecutivo'),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
    path('ejecutivos_asignados', views.asignar_agentes, name="ejecutivos_asignados"),
    path('desasignar_ejecutivo/<int:pk>', views.desasignar_ejecutivo, name="desasignar_ejecutivo"),
   
]

apps/master/urls.py
from django.urls import path
from . import views

app_name = 'master'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.menu, name='menu'),
]

apps/usuarios/urls.py
from django.urls import path
from .formularios import UserLoginForm
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.ListarUsuarios.as_view(), name="index"),
    path('registrar', views.Registrar.as_view(), name="registrar"),
    path('login',views.Login.as_view(authentication_form=UserLoginForm),name='login'),
    path('perfil/<int:pk>',views.Profile.as_view(),name='perfil'),
    path('crear',views.CrearUsuario.as_view(),name='crear'),
    path('editar/<int:pk>',views.EditarUsuario.as_view(),name='editar'),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
]

despachador_correos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500

handler400 = 'despachador_correos.views.bad_request'
handler403 = 'despachador_correos.views.permission_denied'
handler404 = 'despachador_correos.views.page_not_found'
handler500 = 'despachador_correos.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.master.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('configuraciones/', include('apps.configuraciones.urls')),
    path('correos/', include('apps.correos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" class="">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'master/vendor/bootstrap-5.1.3-dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'master/vendor/bootstrap-5.1.3-dist/css/sb-admin-2.css' %}">
    <link rel="stylesheet" href="{% static 'master/vendor/fontawesome-free-5.15.4-web/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'master/vendor/DataTables/datatables.min.css'%} " />
    <link rel="stylesheet"
        href="{% static 'master/vendor/DataTables/ColReorder-1.5.4/css/colReorder.dataTables.min.css'%}" />
    <link rel="stylesheet"
        href="{% static 'master/vendor/DataTables/Responsive-2.2.9/css/responsive.dataTables.min.css'%} " />
    <link rel="stylesheet"
        href="{% static 'master/vendor/DataTables/Buttons-2.0.1/css/buttons.dataTables.min.css'%} " />

    <!-- Fin  -->
    <!-- Icono Navegador -->
    <link rel="shortcut icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <!-- Fin  -->
    <!-- Fin Icono Navegador -->
    <link rel="stylesheet" href="{% static 'master/css/style.css' %}">
    <link rel="stylesheet" href="{% block styles %}{% endblock styles %}">
    <!-- Fin  -->
    <title class="edit_appname">{{appname|capfirst}}</title>
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- sidebar -->
        {% include "sidebar.html" %}
        <!-- End sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include "topbar.html" %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block contenido %}
                    {% endblock contenido %}
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <a href="https://www.telectronic.com"
                            class="mb-3 ms-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                            <span class="text-muted">Copyright &copy; 2020 - <span id="copyright"></span>
                                Telectronic</span>
                        </a>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <script src="{% static 'master/vendor/jquery/jquery-3.6.0.js'  %}"></script>
    <script src="{% static 'master/vendor/jquery/jquery.mask.min.js'  %}"></script>
    <script src="{% static 'master/vendor/jquery/jquery.inputmask.min.js'  %}"></script>

    <script src="{% static 'master/vendor/bootstrap-5.1.3-dist/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'master/vendor/bootstrap-5.1.3-dist/js/sb-admin-2.js' %}"></script>
    <script src="{% static 'master/vendor/bootstrap-5.1.3-dist/js/bootstrap-show-password.min.js'  %}"></script>
    <script src="{% static 'master/vendor/fontawesome-free-5.15.4-web/js/all.js'  %}"></script>

    <script src="{% static 'master/vendor/DataTables/datatables.min.js'%}"></script>

    <!-- Begin of Responsive DataTable -->
    <script src="{% static 'master/vendor/DataTables/ColReorder-1.5.4/js/dataTables.colReorder.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/Responsive-2.2.9/js/dataTables.responsive.min.js'%}"></script>
    <!-- End of Responsive DataTable -->

    <!-- Begin of Buttons DataTable -->
    <script src="{% static 'master/vendor/DataTables/Buttons-2.0.1/js/dataTables.buttons.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/JSZip-2.5.0/jszip.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/pdfmake-0.1.36/pdfmake.min.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/pdfmake-0.1.36/vfs_fonts.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/Buttons-2.0.1/js/buttons.html5.js'%}"></script>
    <script src="{% static 'master/vendor/DataTables/Buttons-2.0.1/js/buttons.print.min.js'%}"></script>
    <!-- End of Buttons DataTable -->

    <script src="{% static 'master/vendor/jquery-easing/jquery.easing.min.js'  %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@latest/dist/Chart.min.js"></script>

    <script>
        //add to id copyright year now
        $("form").on('submit', function (e) {
            $("#submit-id-submit").fadeOut();
        });
        var year = new Date().getFullYear();
        $("#copyright").html(year);

        $("#nav-{{appname}}").parent().parent().addClass('show');
        $("#nav-{{appname}}").addClass("active")
        var printCounter = 0;
        $('#tabla_base').DataTable({
            rowReorder: {
                selector: 'td:nth-child(2)'
            },
            responsive: true,
            "language": {
                "url": "{% static 'master/vendor/DataTables/Spanish.json'%}",
            },
            dom: 'lBfrtip',
            buttons: [
                'copy',
                {
                    extend: 'excel',
                    title: '{{appname}}',
                    messageTop: null
                },
                {
                    extend: 'pdf',
                    title: '{{appname}}',
                    messageBottom: null
                },
                {
                    extend: 'print',
                    title: '{{appname}}',

                    messageTop: function () {
                        printCounter++;

                        if (printCounter === 1) {
                            return 'Esta es la primera vez que imprime este documento.';
                        } else {
                            return 'Has impreso este documento ' + printCounter + ' Veces';
                        }
                    },
                    messageBottom: null
                }
            ],
        });


        $('.edit_appname').text(function (index, text) {
            return text.replace(/_/g, ' ');
        });

        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
    {% block javascript %}
    {% endblock javascript%}
</body>

</html>

templates/errors.html
<!DOCTYPE html>
<html lang="en" class="">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <!-- Icono Navegador -->
    <link rel="shortcut icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <!-- Fin  -->
    <!-- Fin Icono Navegador -->
    <link rel="stylesheet" href="{% static 'master/css/style_404.css' %}">
    <link rel="stylesheet" href="{% block styles %}{% endblock styles %}">
    <!-- Fin  -->
    <title class="edit_appname">{{code}}</title>
</head>

<body>
    <div class="moon"></div>
    <div class="moon__crater moon__crater1"></div>
    <div class="moon__crater moon__crater2"></div>
    <div class="moon__crater moon__crater3"></div>

    <div class="star star1"></div>
    <div class="star star2"></div>
    <div class="star star3"></div>
    <div class="star star4"></div>
    <div class="star star5"></div>

    <div class="error">
        <div class="error__title">{{code}}</div>
        <div class="error__subtitle">Hmmm...</div>
        <div class="error__description">Parece que uno de los desarrolladores se quedó dormido</div>
        <a class="error__button error__button--active" href="{% url 'master:index' %}">Home</a>
        <a class="error__button" href="https://www.telectronic.com">Contacto</a>
    </div>

    <div class="astronaut">
        <div class="astronaut__backpack"></div>
        <div class="astronaut__body"></div>
        <div class="astronaut__body__chest"></div>
        <div class="astronaut__arm-left1"></div>
        <div class="astronaut__arm-left2"></div>
        <div class="astronaut__arm-right1"></div>
        <div class="astronaut__arm-right2"></div>
        <div class="astronaut__arm-thumb-left"></div>
        <div class="astronaut__arm-thumb-right"></div>
        <div class="astronaut__leg-left"></div>
        <div class="astronaut__leg-right"></div>
        <div class="astronaut__foot-left"></div>
        <div class="astronaut__foot-right"></div>
        <div class="astronaut__wrist-left"></div>
        <div class="astronaut__wrist-right"></div>

        <div class="astronaut__cord">
            <canvas id="cord" height="500px" width="500px"></canvas>
        </div>

        <div class="astronaut__head">
            <canvas id="visor" width="60px" height="60px"></canvas>
            <div class="astronaut__head-visor-flare1"></div>
            <div class="astronaut__head-visor-flare2"></div>
        </div>
    </div>
    <script>
        function drawVisor() {
            const canvas = document.getElementById('visor');
            const ctx = canvas.getContext('2d');

            ctx.beginPath();
            ctx.moveTo(5, 45);
            ctx.bezierCurveTo(15, 64, 45, 64, 55, 45);

            ctx.lineTo(55, 20);
            ctx.bezierCurveTo(55, 15, 50, 10, 45, 10);

            ctx.lineTo(15, 10);

            ctx.bezierCurveTo(15, 10, 5, 10, 5, 20);
            ctx.lineTo(5, 45);

            ctx.fillStyle = '#2f3640';
            ctx.strokeStyle = '#f5f6fa';
            ctx.fill();
            ctx.stroke();
        }

        const cordCanvas = document.getElementById('cord');
        const ctx = cordCanvas.getContext('2d');

        let y1 = 160;
        let y2 = 100;
        let y3 = 100;

        let y1Forward = true;
        let y2Forward = false;
        let y3Forward = true;

        function animate() {
            requestAnimationFrame(animate);
            ctx.clearRect(0, 0, innerWidth, innerHeight);

            ctx.beginPath();
            ctx.moveTo(130, 170);
            ctx.bezierCurveTo(250, y1, 345, y2, 400, y3);

            ctx.strokeStyle = 'white';
            ctx.lineWidth = 8;
            ctx.stroke();


            if (y1 === 100) {
                y1Forward = true;
            }

            if (y1 === 300) {
                y1Forward = false;
            }

            if (y2 === 100) {
                y2Forward = true;
            }

            if (y2 === 310) {
                y2Forward = false;
            }

            if (y3 === 100) {
                y3Forward = true;
            }

            if (y3 === 317) {
                y3Forward = false;
            }

            y1Forward ? y1 += 1 : y1 -= 1;
            y2Forward ? y2 += 1 : y2 -= 1;
            y3Forward ? y3 += 1 : y3 -= 1;
        }

        drawVisor();
        animate();
    </script>
</body>

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="row">
    <div class="col-xl-6 col-md-6 mb-4" id="llamadas_ingresadas">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">
	                    <a href="{% url 'correos:ejecutivos_asignados' %}">EJECUTIVOS ASIGNADOS</a>
			</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{ejecutivos}}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users-cog fa-2x text-gray-300"></i>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-6 col-md-6 mb-4" id="llamadas_contestadas">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary mb-1">
			    <a href="{% url 'correos:correos' %}">CORREOS DESPACHADOS HOY</a>
			</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            {{correos_despachados}}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-envelope fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-12 col-lg-12">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">CORREOS DESPACHADOS POR DIA</h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div style="width: 100%;">
                    <canvas id="chartFechas"></canvas>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock contenido %}
{% block javascript %}

<script>
    $(document).ready(function () {

        var ctx = document.getElementById('chartFechas').getContext('2d');
        var datos_correos = '{{registros_por_dia|safe}}';

        var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'bar',
            // use datos_correos
            data: {
                labels: JSON.parse(datos_correos).map(function (e) {
                    return e.dia;
                }),
                datasets: [{
                    label: 'Correos despachados por dia',
                    backgroundColor: 'rgba(40, 23, 172, 0.687)',
                    borderColor: 'rgba(40, 23, 172, 0.687)',
                    data: JSON.parse(datos_correos).map(function (e) {
                        return e.cantidad;
                    }),
                }]
            },
	options: {
    		scales: {
      		yAxes: [{
       		ticks: {
         	beginAtZero: true,
          	min: 0,
          	
        }
      }]
    }
  }
        });
    });
</script>

{% endblock javascript %}

templates/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-corus-sidebar sidebar sidebar-dark accordion fs-3 text" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center m-1" href="/">
        <div class="sidebar-brand-icon ">
            <img src="{% static 'master/img/logo_chubb.webp' %}" alt="logo" class="img-fluid">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li id="nav-dashboard" class="nav-item ">
        <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        General
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    {% if user.is_superuser  %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-bs-toggle="collapse"
            data-bs-target="#collapseSA" aria-expanded="false" aria-controls="collapseSA">
            <i class="fas fa-brain"></i>
            <span>Super-Admin</span>
        </a>
        <div id="collapseSA" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionSidebar">
            <div class="bg-white py-2 font-weight-bold collapse-inner rounded">
                <a id="nav-usuarios" class="collapse-item font-weight-bold"
                    href="{% url 'usuarios:index' %}">Usuarios</a>
                <a id="nav-casillas" class="collapse-item font-weight-bold"
                    href="{% url 'configuraciones:casillas' %}">Casillas</a>
                <a id="nav-configuraciones" class="collapse-item font-weight-bold"
                    href="{% url 'configuraciones:crear_configuracion' %}">Configuraciones</a>
            </div>
        </div>
    </li>

    {% endif %}
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-bs-toggle="collapse"
            data-bs-target="#collapseCorreo" aria-expanded="false" aria-controls="collapseCorreo">
            <i class="far fa-envelope"></i>
            <span>Correos</span>
        </a>
        <div id="collapseCorreo" class="accordion-collapse collapse" aria-labelledby="headingOne"
            data-bs-parent="#accordionSidebar">
            <div class="bg-white py-2 font-weight-bold collapse-inner rounded">
                <a id="nav-correos_procesados" class="collapse-item font-weight-bold"
                    href="{% url 'correos:correos' %}">Procesados</a>
                <a id="nav-ejecutivos" class="collapse-item font-weight-bold"
                    href="{% url 'correos:ejecutivos' %}">Ejecutivos</a>
                <a id="nav-asignacion_ejecutivos" class="collapse-item font-weight-bold"
                    href="{% url 'correos:ejecutivos_asignados' %}">Asignar Ejecutivos</a>

            </div>

        </div>
    </li>

    <!-- Sidebar Toggler (Sidebar) -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
{% block javascript %}

{% endblock javascript %}

templates/topbar.html
{% load static %}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <div class="d-sm-flex align-items-center justify-content-between ">
        <h1 id="edit_appname" class="h4 mb-0 text-danger edit_appname">{{appname|upper}}</h1>
    </div>
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->

        <li class="nav-item dropdown no-arrow">
            <!-- <a class="nav-link disabled text-dark">CHUBB CHILE</a>-->
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle  " href="#" id="navbarDropdownMenuLink" role="button"
                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Bienvenido {{user.first_name}}</span>
                <img class="img-profile rounded-circle" src="{% static 'master/img/LogoN.svg' %}">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'usuarios:perfil' pk=user.id%}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cerrar Sesión
                </a>
            </div>
        </li>
    </ul>
</nav>

<div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Confirma?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body-logout ms-4 p-3">Estás seguro que quieres finalizar sesión?.</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <a class="btn btn-danger" href="{% url 'logout' %}">Salir</a>
            </div>
        </div>
    </div>
</div>