apps/correos/urls.py
from django.urls import path

from . import views

app_name = 'correos'

urlpatterns = [
    path('', views.ListarCorreos.as_view(), name="correos"),
    path('ejecutivos', views.ListarEjecutivos.as_view(), name="ejecutivos"),
    path('crear_ejecutivo',views.CrearEjecutivo.as_view(),name='crear_ejecutivo'),
    path('editar_ejecutivo/<int:pk>',views.EditarEjecutivo.as_view(),name='editar_ejecutivo'),
    path('predestroy/<int:pk>',views.predestroy,name='predestroy'),
    path('destroy/<int:pk>',views.destroy,name='destroy'),
    path('ejecutivos_asignados', views.asignar_agentes, name="ejecutivos_asignados"),
    path('desasignar_ejecutivo/<int:pk>', views.desasignar_ejecutivo, name="desasignar_ejecutivo"),
   
]

apps/master/urls.py
from django.urls import path
from . import views

app_name = 'master'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/', views.menu, name='menu'),
]

despachador_correos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404, handler500

handler400 = 'despachador_correos.views.bad_request'
handler403 = 'despachador_correos.views.permission_denied'
handler404 = 'despachador_correos.views.page_not_found'
handler500 = 'despachador_correos.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.master.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('configuraciones/', include('apps.configuraciones.urls')),
    path('correos/', include('apps.correos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/correos/models.py
from django.db import models
from apps.usuarios.models import *
from apps.configuraciones.models import *
from .models import Usuario,  Configuracion


# Create your models here.
class Estado(models.Model):
    nombre = models.CharField(max_length=255,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre
        
class Ejecutivo(models.Model):
    updated_at = models.DateTimeField(auto_now=True)
    usuario=models.ForeignKey(Usuario, on_delete=models.PROTECT)
    
def get_email(usuario): 
    return usuario.email

class Correo(models.Model):
    subject = models.CharField(max_length=255,blank=True,null=True)
    body = models.TextField(blank=True,null=True)
    desde = models.CharField(max_length=255,blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    ejecutivo = models.ForeignKey(Usuario, on_delete=models.PROTECT, blank=True, null=True)    
    configuracion = models.ForeignKey(Configuracion, on_delete=models.PROTECT)
    estado = models.ForeignKey(Estado, on_delete=models.PROTECT)

apps/correos/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from .models import Correo, Usuario,Ejecutivo
import datetime
from .formularios import FormularioNuevoEjecutivo, FormularioAsignarEjecutivo

# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListarCorreos(ListView):
    template_name = 'correos/correos_list.html'
    model = Correo

    def get_context_data(self, **kwargs):
        context = super(ListarCorreos, self).get_context_data(**kwargs)
        context['appname'] = "correos_procesados"
        fecha_ini = self.request.GET.get('fecha_ini')
        fecha_fin = self.request.GET.get('fecha_fin')
        tipo= self.request.GET.get('tipo')
        if fecha_ini and fecha_fin:
            context['fecha_ini'] = fecha_ini
            context['fecha_fin'] = fecha_fin
        else:
            context['fecha_ini'] = datetime.datetime.now().strftime("%Y-%m-%d 00:00")
            context['fecha_fin'] = datetime.datetime.now().strftime("%Y-%m-%d 23:59")
        if tipo:
            context['tipo'] = tipo
        else:
            context['tipo'] = 0
        return context
        
    def get_queryset(self):
        fecha_ini = self.request.GET.get('fecha_ini')
        fecha_fin = self.request.GET.get('fecha_fin')
        if not fecha_ini:
            fecha_ini = datetime.datetime.now().strftime("%Y-%m-%d 00:00")
        if not fecha_fin:
            fecha_fin = datetime.datetime.now().strftime("%Y-%m-%d 23:59")
        tipo= self.request.GET.get('tipo')
        valor=self.request.GET.get('valor')
        if valor != "":
            #consultar por Ejecutivo
            if tipo == "1":
                return Correo.objects.filter(created_at__range = (fecha_ini,fecha_fin), ejecutivo__email__icontains = valor )
            #consultar por Remitente
            if tipo == "2":
                return Correo.objects.filter(created_at__range = (fecha_ini,fecha_fin), desde__icontains = valor )
            #consultar por Subject
            if tipo == "3":
                return Correo.objects.filter(created_at__range = (fecha_ini,fecha_fin), subject__icontains = valor )
            #consultar por Estado
            if tipo == "4":
                return Correo.objects.filter(created_at__range = (fecha_ini,fecha_fin), estado__nombre__icontains = valor )
        #solo por fecha
        else:
            return Correo.objects.filter(created_at__range = (fecha_ini,fecha_fin))
        
    def get(self, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return super().get(*args, **kwargs)
        else:
            return redirect(reverse_lazy('master:menu'))
    
@method_decorator(login_required, name='dispatch')
class ListarEjecutivos(ListView):
    template_name = 'correos/ejecutivos_list.html'
    model = Usuario

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['appname'] = "ejecutivos"
        return context
    
    def get(self, *args, **kwargs):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return super().get(*args, **kwargs)
        else:
            return redirect('master:menu')
    
    def get_queryset(self):
        return Usuario.objects.filter(is_superuser = False, is_staff = False, is_active = True)

@method_decorator(login_required, name='dispatch')
class CrearEjecutivo(CreateView):
    template_name = "correos/ejecutivos.html"
    form_class = FormularioNuevoEjecutivo
    model= Usuario
    success_url = reverse_lazy("correos:ejecutivos")

    def form_valid(self,form):
        usuario = form.save(commit = False)
        usuario.username = usuario.email
        usuario.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CrearEjecutivo, self).get_context_data(**kwargs)
        context['legend'] = "Nuevo Ejecutivo"
        context['appname'] = "ejecutivos"
        return context
    
    def get(self, request):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return super().get(request)
        return redirect("master:index")        

@method_decorator(login_required, name='dispatch')
class EditarEjecutivo(UpdateView):
    template_name = "formularios/generico.html"
    model = Usuario
    form_class = FormularioNuevoEjecutivo
    success_url = reverse_lazy("correos:ejecutivos")

    def get_context_data(self, **kwargs):
        context = super(EditarEjecutivo, self).get_context_data(**kwargs)
        context['legend'] = "Editar Ejecutivo"
        context['appname'] = "Ejecutivos"
        return context
    
    def form_valid(self,form):
        usuario = form.save(commit = False)
        usuario.username = usuario.email
        usuario.save()
        return super().form_valid(form)

    def get(self, request,pk):
        if self.request.user.is_superuser:
            return super().get(request)
        return redirect("master:index")

@login_required(login_url="/")
def predestroy(request,pk):
    if request.method == "GET":
        try:
            usuario = Usuario.objects.get(id=pk)
        except:
            return redirect("usuarios:index")
        context={
            'id' : usuario.id,
            'nombre': usuario.first_name,
            'apellido' : usuario.last_name,
            'email' : usuario.email,
        }
        return JsonResponse(context)
    return redirect("correos:ejecutivos")

@login_required(login_url="/")
def destroy(request,pk):
    if request.method == "GET":
        if request.user.is_superuser:
            try:
                usuario = Usuario.objects.get(id=pk)
            except:
                return redirect("correos:ejecutivos")
            usuario.is_active = False
            usuario.save()
    return redirect("correos:ejecutivos")    

@login_required(login_url="/")
def asignar_agentes(request):
    if request.method == "GET":
        form = FormularioAsignarEjecutivo()
        asignados = Ejecutivo.objects.all()
        context = {
            'form' : form,
            'object_list' : asignados,
            'legend' : "Asignar Ejecutivos",
            'appname' : "asignacion_ejecutivos",
        }
        return render(request, "correos/ejecutivos_asignados.html", context)
    elif request.method == "POST":
        if "ejecutivos" in request.POST:
            ejecutivos = request.POST.getlist('ejecutivos')
            for ejecutivo in ejecutivos:
                Ejecutivo.objects.create(usuario_id = ejecutivo)
                usuario = Usuario.objects.get(id = ejecutivo)
                usuario.asignado = True
                usuario.save()
            messages.success(request, "Ejecutivos asignados correctamente",extra_tags="success")
        else:
            messages.success(request, "No se ha seleccionado ningún ejecutivo",extra_tags="danger")
    return redirect("correos:ejecutivos_asignados")

@login_required(login_url="/")
def desasignar_ejecutivo(request,pk):
    if request.method == "GET":
        try:
            ejecutivo = Ejecutivo.objects.get(usuario_id = pk)
        except:
            messages.success(request, "Ejecutivo no encontrado",extra_tags="danger")
            return redirect("correos:ejecutivos_asignados")
        ejecutivo.delete()
        usuario = Usuario.objects.get(id = ejecutivo.usuario.id)
        usuario.asignado = False
        usuario.save()
        messages.success(request, "Ejecutivo desasignado correctamente",extra_tags="success")
    return redirect("correos:ejecutivos_asignados")

templates/correos/correos_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
</div>
<div>
    <form action="{% url 'correos:correos' %}" method="GET" class="form-inline">
        <div class="form-group mx-sm-3 mb-2">
            <label for="fecha_ini" class="me-1">Fecha Inicio: </label>
            <input type="datetime-local" class="form-control" id="fecha_ini" name="fecha_ini"
                placeholder="Fecha Inicio">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="fecha_fin" class="me-1">Fecha Fin: </label>
            <input type="datetime-local" class="form-control" id="fecha_fin" name="fecha_fin" placeholder="Fecha Fin">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="fecha_fin" class="me-1">Tipo: </label>
            <select name="tipo" id="tipo" class="form-control" placeholder="Tipo">
                <option value="0">Busqueda por fecha</option>
                <option value="1">Ejecutivo</option>
                <option value="2">Remitente</option>
                <option value="3">Subject</option>
                <option value="4">Estado</option>
            </select>
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label class="me-1">Valor: </label>
            <input type="text" class="form-control" id="valor" name="valor" placeholder="Valor">
        </div>


        <button type="submit" class="btn btn-primary mb-2">Buscar</button>
    </form>

</div>
<div class=" mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Ejecutivo</th>
                <th>Subject</th>
                <th>Remitente</th>
                <th>Estado</th>
                <th>Última Actualización</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for correo in object_list %}
            <tr>
                <td>{{correo.id}}</td>
                <td>{{correo.ejecutivo.email}}</td>
                <td>{{correo.subject}}</td>
                <td>{{correo.desde}}</td>
                <td>{{correo.estado}}</td>
                <td>{{correo.updated_at|date:'d/m/Y H:i:s'}}</td>
                <td>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#myModal{{correo.id}}">Ver
                        correo</button>
                </td>
            </tr>

            <!-- Modal modal_correo -->
            <div class="modal fade" id="myModal{{correo.id}}" tabindex="-1" body-correo="{{correo.body}}"
                id-correo="{{correo.id}}" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Asunto: {{correo.subject}}</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
                        </div>
                        <div class="modal-body">
                            <h6>Remitente: {{correo.desde}}</h6>
                            <div id="email_body_{{correo.id}}" class="p-3">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock contenido %}

{% block javascript %}
<script>
    //when open modal myModal{{correo.id}} parse email body to html

    $('.modal').on('show.bs.modal', function (event) {
        console.log('abriendo modal');
        body = this.getAttribute('body-correo');
        id_correo = this.getAttribute('id-correo');
        var modal = $(this)
        modal.find('.modal-body #email_body_' + id_correo).html(body);
    })

    //when close modal remove email body
    $('.modal').on('hidden.bs.modal', function (event) {
        console.log('cerrando modal');
        id_correo = this.getAttribute('id-correo');
        var modal = $(this)
        modal.find('.modal-body #email_body_' + id_correo).html('');
    })


    if ('{{fecha_ini}}' != 'None' && '{{fecha_ini}}' != '') {
        $('#fecha_ini').val('{{fecha_ini}}');
    } else {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd + 'T00:00';
        $('#fecha_ini').val(today);
    }
    //if fecha_fin from request.get form set value to input else set value to today date at 00:00
    if ('{{fecha_fin}}' != 'None' && '{{fecha_fin}}' != '') {
        $('#fecha_fin').val('{{fecha_fin}}');
    } else {
        var today = new Date();
        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!
        var yyyy = today.getFullYear();

        if (dd < 10) {
            dd = '0' + dd;
        }

        if (mm < 10) {
            mm = '0' + mm;
        }

        today = yyyy + '-' + mm + '-' + dd + 'T23:59';
        $('#fecha_fin').val(today);
    }
    $('#tipo').val('{{tipo}}');
</script>
{% endblock javascript %}

templates/correos/ejecutivos.html
{% extends user.is_authenticated|yesno:"base.html,registration/base_login.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

{% if user.is_authenticated %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <button onclick="history.back()" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Atrás</button>
</div>
<div class="col-8 p-3 mx-auto border border-primary">
    <form enctype="multipart/form-data" class="text-dark" method="POST" class="rounded-3 text-white">
        {% else %}
        <form enctype="multipart/form-data" method="POST" class="rounded-3 text-white">
            {% endif %}
            <h2 class="text-center">{{legend}}</h2>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% csrf_token %}
            {% crispy form %}
        </form>
</div>

{% endblock contenido %}

templates/correos/ejecutivos_asignados.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="mb-3 mt-3 container col-12">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-xl-6 col-md-6 mb-4">
            <h3 class="text-center">{{legend}}</h3>
            <form enctype="multipart/form-data" class="text-dark" method="POST" class="rounded-3 text-white">
                {% csrf_token %}
                {% crispy form %}
            </form>
        </div>
        <div class="col-xl-6 col-md-6 ">
            <h3 class="text-center ">Agentes asignados</h3>
            <br>
            <table id="" class="table table-striped table-hover table-borderless table-bordered" style="width:100%">
                <thead class="">
                    <tr>
                        <th>Ejecutivo</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in object_list %}
                    <tr>
                        <td style="vertical-align: middle;">{{elemento.usuario.email}}</td>
                        <td style="vertical-align: middle;">
                            <a class="btn btn-danger btn-sm text-light border border-dark m-1"
                                href="{% url 'correos:desasignar_ejecutivo' pk=elemento.usuario.id %}">
                                <i class="fas fa-trash"></i> </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock contenido %}
{% block javascript %}
<script>
</script>
{% endblock javascript %}

templates/correos/ejecutivos_list.html
{% extends 'base.html' %}
{% load static %}
{% block contenido%}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 mb-1 btn btn-primary text-light border"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
    <a href="{% url 'correos:crear_ejecutivo' %}" class="align-self-center ms-2 mb-1 btn btn-success text-light border"><i
            class="fas fa-plus-circle"></i> Agregar Ejecutivo</a>
</div>

<div class=" mt-3">
    <table id="tabla_base" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for usuario in object_list %}
            <tr>
                <td>{{usuario.id}}</td>
                <td>{{usuario.first_name}}</td>
                <td>{{usuario.last_name}}</td>
                <td>{{usuario.email}}</td>
                <td>
                    {% if not usuario.is_superuser %}
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'correos:editar_ejecutivo' pk=usuario.id %}" usuario="{{usuario.id}}" id="edit"><i
                            class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'correos:predestroy' pk=usuario.id %}" href="">
                        <i class="fas fa-trash"></i> </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header" notempty='not'>
                <h5 class="modal-title " id="modalLabel" notempty='not'>¿Desea Eliminar al siguiente
                    Usuario?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>

            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

{% block javascript %}
<script>
    $(".dataTable").on('click', '.open-modal', function () {
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                Datos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'] + " " + data['apellido'] +
                    "</p> <p notempty='not'> Email: " +
                    data['email'] +
                    "</p>";
                $(".modal-body").append(Datos);
                $("#delete").click(function () {
                    window.location.href = "/correos/destroy/" + data["id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}